services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=autoanime
      - POSTGRES_PASSWORD=autoanime
      - POSTGRES_DB=autoanime
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoanime"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
#    network_mode: "host"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
#    network_mode: "host"

volumes:
  postgres_data: