---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/media:/media #optional
    ports:
      - 8989:8989
    restart: unless-stopped